server:
  port: 8085
  servlet:
    context-path: /fs
  connection-timeout: 30000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240
  tomcat:
    accept-count: 250
    max-connections: 25000
    max-threads: 500
    min-spare-threads: 60
    accesslog:
      enabled: true
      prefix: access-log
      file-date-format: .yyyy-MM-dd
      suffix: .log
      pattern: '%t %a "%r" %s %D'

spring:
  elasticsearch.rest:
    username: 'elastic'
    password: '6l2suDT5cLpESK-j2o5H'
    host: 'localhost'
    port: '9200'
    method: 'https'
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: file-search-master
  datasource:
    url: jdbc:postgresql://localhost:5432/file_content_search?currentSchema=fs
    username: db_user
    password: password

management.health.elasticsearch.enabled: false

files-config:
  tenants:
    - name: zkip
      file-resource:
        s3:
          access-key: ----
          secret-key: ----
          buckets:
            - name: fs-search
              url: arn:aws:s3:::fs-search
              region: me-south-1

